version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "package-lock.json" }}
            - npm-deps-
      - run:
          name: Install Deps
          command: |
            npm install
            echo "export PATH=${PATH}:node_modules/.bin" >> $BASH_ENV
      - run:
          name: Create Hub Key
          command: |
            mkdir keys
            echo ${DEVHUB_SERVER_KEY_BASE64} | base64 -d >> keys/server.key
      - run:
          name: Lint
          command: |
            npm run lint
      - run:
          name: Build
          command: |
            npm run build
      - run:
          name: Setup Scratch Org
          command: |
            echo $PATH
            sfdx force:auth:jwt:grant -i ${DEVHUB_CLIENT_ID} -f keys/server.key -u ${DEVHUB_USERNAME} -d -a hub
            sfdx force:org:create -f config/project-scratch-def.json -a circle_build_${CIRCLE_BUILD_NUM} -s --wait 5 
            sfdx force:user:create -f config/user-def.json -a circle_build_${CIRCLE_BUILD_NUM}_user01 
      - run:
          name: Test
          command: |
            SFDX_USERNAME=circle_build_${CIRCLE_BUILD_NUM} npm run test
      - run:
          name: Delete Useless Scratch Org
          command: |
            sfdx force:org:delete -u circle_build_${CIRCLE_BUILD_NUM} -p
      - save_cache:
          key: npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ~/workspace/node_modules
